// NOTE - this is generated by unicode_ranges.pl, but modified for Raku
module.exports = {
  // Raku allows hyphens in identifiers - simple approach
  identifier: /[_\p{XID_Start}][\p{XID_Continue}\-]*/v,

  // bareword adds :: support like before, but with the new identifier rules
  bareword:   /((::)|([_\p{XID_Start}][\p{XID_Continue}\-]*))+/v,
}
