name: Fuzz De Parser
on:
  push:
    paths: 
      - src/scanner.c
  workflow_dispatch:
jobs:
  test:
    name: Fuzz Parser
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: vigoux/tree-sitter-fuzz-action@v1
        with:
          language: perl
          external-scanner: src/scanner.c
          time: 60
